databases:
  - name: todorails
    databaseName: todorails
    user: todorails

services:
  - type: web
    name: todorails
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todorails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false